package baiducloud

const (
	BaiduCloudTestResourceName              = "default"
	BaiduCloudTestResourceTypeName          = "tf-test-acc"
	BaiduCloudTestResourceTypeNameUnderLine = "tf_test_acc"

	BaiduCloudTestResourceTypeNameAcl                 = BaiduCloudTestResourceTypeName + "-" + "acl"
	BaiduCloudTestResourceTypeNameAppblb              = BaiduCloudTestResourceTypeName + "-" + "appblb"
	BaiduCloudTestResourceTypeNameAppblbListener      = BaiduCloudTestResourceTypeName + "-" + "appblb-listener"
	BaiduCloudTestResourceTypeNameAppblbServerGroup   = BaiduCloudTestResourceTypeName + "-" + "appblb-server-group"
	BaiduCloudTestResourceTypeNameblb                 = BaiduCloudTestResourceTypeName + "-" + "blb"
	BaiduCloudTestResourceTypeNameAutoSnapshotPolicy  = BaiduCloudTestResourceTypeName + "-" + "auto-snapshot-policy"
	BaiduCloudTestResourceTypeNameBosBucket           = BaiduCloudTestResourceTypeName + "-" + "bos-bucket"
	BaiduCloudTestResourceTypeNameBosBucketObject     = BaiduCloudTestResourceTypeName + "-" + "bos-bucket-object"
	BaiduCloudTestResourceTypeNameCcev2Cluster        = BaiduCloudTestResourceTypeName + "-" + "ccev2-cluster"
	BaiduCloudTestResourceTypeNameCcev2Instance       = BaiduCloudTestResourceTypeName + "-" + "ccev2-instance"
	BaiduCloudTestResourceTypeNameCcev2InstanceGroup  = BaiduCloudTestResourceTypeName + "-" + "ccev2-instance-group"
	BaiduCloudTestResourceTypeNameCds                 = BaiduCloudTestResourceTypeName + "-" + "cds"
	BaiduCloudTestResourceTypeNameCdsAttachment       = BaiduCloudTestResourceTypeName + "-" + "cds-attachment"
	BaiduCloudTestResourceTypeNameCert                = BaiduCloudTestResourceTypeName + "-" + "cert"
	BaiduCloudTestResourceTypeNameCfcAlias            = BaiduCloudTestResourceTypeName + "-" + "cfc-alias"
	BaiduCloudTestResourceTypeNameCfcFunction         = BaiduCloudTestResourceTypeName + "-" + "cfc-function"
	BaiduCloudTestResourceTypeNameCfcTrigger          = BaiduCloudTestResourceTypeName + "-" + "cfc-trigger"
	BaiduCloudTestResourceTypeNameCfcVersion          = BaiduCloudTestResourceTypeName + "-" + "cfc-version"
	BaiduCloudTestResourceTypeNameEip                 = BaiduCloudTestResourceTypeName + "-" + "eip"
	BaiduCloudTestResourceTypeNameEipAssociation      = BaiduCloudTestResourceTypeName + "-" + "eip-association"
	BaiduCloudTestResourceTypeNameInstance            = BaiduCloudTestResourceTypeName + "-" + "instance"
	BaiduCloudTestResourceTypeNameNatGateway          = BaiduCloudTestResourceTypeName + "-" + "nat-gateway"
	BaiduCloudTestResourceTypeNameNatSnatRule         = BaiduCloudTestResourceTypeName + "-" + "nat-snat-rule"
	BaiduCloudTestResourceTypeNamePeerConn            = BaiduCloudTestResourceTypeName + "-" + "peer-conn"
	BaiduCloudTestResourceTypeNamePeerConnAcceptor    = BaiduCloudTestResourceTypeName + "-" + "peer-conn-acceptor"
	BaiduCloudTestResourceTypeNameRdsAccount          = BaiduCloudTestResourceTypeName + "-" + "rds-account"
	BaiduCloudTestResourceTypeNameRdsInstance         = BaiduCloudTestResourceTypeName + "-" + "rds-instance"
	BaiduCloudTestResourceTypeNameRdsReadonlyInstance = BaiduCloudTestResourceTypeName + "-" + "rds-readonly-instance"
	BaiduCloudTestResourceTypeNameRouteRule           = BaiduCloudTestResourceTypeName + "-" + "route-rule"
	BaiduCloudTestResourceTypeNameScs                 = BaiduCloudTestResourceTypeName + "-" + "scs"
	BaiduCloudTestResourceTypeNameSecurityGroup       = BaiduCloudTestResourceTypeName + "-" + "security-group"
	BaiduCloudTestResourceTypeNameSecurityGroupRule   = BaiduCloudTestResourceTypeName + "-" + "security-group-rule"
	BaiduCloudTestResourceTypeNameSnapshot            = BaiduCloudTestResourceTypeName + "-" + "snapshot"
	BaiduCloudTestResourceTypeNameSubnet              = BaiduCloudTestResourceTypeName + "-" + "subnet"
	BaiduCloudTestResourceTypeNameVpc                 = BaiduCloudTestResourceTypeName + "-" + "vpc"
	BaiduCloudTestResourceTypeNameLocalDnsPrivatezone = BaiduCloudTestResourceTypeName + "-" + "localdns-privatezone"
	BaiduCloudTestResourceTypeNameLocalDnsVPC         = BaiduCloudTestResourceTypeName + "-" + "localdns-vpc"
	BaiduCloudTestResourceTypeNameBbcImage            = BaiduCloudTestResourceTypeName + "-" + "bbc-image"
	BaiduCloudTestResourceTypeNameBbcInstance         = BaiduCloudTestResourceTypeName + "-" + "bbc-instance"
)
